---
- hosts: "{{host}}"
  become: true
  tasks:

  - name: Install Packages
    yum:
      name: "{{item}}"
      state: present
    with_items:
      - java-1.8.0
      - tomcat
      - tomcat-webapps
      - tomcat-admin-webapps

  - name: Copy tomcat users file to tomcat server
    copy:
      src: tomcat-users.xml
      dest: /etc/tomcat/tomcat-users.xml
      
  - name: Delete old version
    file:
      path: /usr/share/tomcat/webapps/*.war
      state: absent      

  - name: Deploy Artifacts to tomcat server
    get_url:
      url: http://34.223.41.68:8081/nexus/service/local/repositories/gol/content/Dev/dev/{{VERSION}}/dev-{{VERSION}}.war
      url_username: admin
      password: admin123
      dest: /usr/share/tomcat/webapps/
      
  - name: Restart Tomcat Server
    service:
      name: tomcat
      state: restarted



