---
- hosts: "{{host}}"
  become: true
  tasks:

  - name: Install Packages
    yum:
      name: "{{item}}"
      state: present
    with_items:
      - java-1.8.0
      - python3
      - python3-pip

  - name: Install pip packages
    pip:
      name: "{{ item }}"
      executable: pip3
    loop:
      - boto3
      - botocore   

  - name: Download Tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.105/bin/apache-tomcat-9.0.105.tar.gz
      dest: /home/user1/
      mode: 0777
      owner: user1
      group: user1

  - name: Extract Tomcat
    unarchive:
      src: /home/user1/apache-tomcat-9.0.105.tar.gz
      dest: /home/user1/
      owner: user1
      group: user1
      remote_src: yes

  - name: Copy tomcat users file to tomcat server
    copy:
      src: tomcat-users.xml
      dest: /home/user1/apache-tomcat-9.0.105/conf/tomcat-users.xml

  - name: Copy context.xml
    copy:
      src: context.xml
      dest: /home/user1/apache-tomcat-9.0.105/webapps/manager/META-INF/context.xml


  - name: Stop Tomcat server
    shell: ./shutdown.sh
    args:
      chdir: /home/user1/apache-tomcat-9.0.105/bin

  - name: Deploy Gameof Life.war
    amazon.aws.s3_object:
      access_key: "{{Access_key}}"
      secret_key: "{{Secret_Key}}"
      bucket: gameoflife-12345678
      object: gameoflife.war
      dest: /home/user1/apache-tomcat-9.0.105/webapps
      mode: get      
      
  - name: Start Tomcat
    shell: ./startup.sh
    args:
      chdir: /home/user1/apache-tomcat-9.0.105/bin

      
