---
- hosts: "{{host}}"
  become: true
  tasks:

  - name: Install Packages
    yum:
      name: "{{item}}"
      state: present
    with_items:
      - java-1.8.0

  - name: Download Tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.105/bin/apache-tomcat-9.0.105.tar.gz
      dest: /home/user1/

  - name: Extract Tomcat
    unarchive:
      src: /home/user1/apache-tomcat-9.0.105.tar.gz
      dest: /home/user1/      

  - name: Copy tomcat users file to tomcat server
    copy:
      src: tomcat-users.xml
      dest: /home/user1/apache-tomcat-9.0.105/conf/tomcat-users.xml

  - name: Deploy Artifacts to tomcat server
    get_url:
      url: http://34.223.41.68:8081/nexus/service/local/repositories/gol/content/Dev/dev/{{VERSION}}/dev-{{VERSION}}.war
      url_username: admin
      password: admin123
      dest: /usr/share/tomcat/webapps/
      
  - name: Restart Tomcat Server
    service:
      name: tomcat
      state: restarted


