---
- hosts: "{{host}}"
  become: true
  tasks:

  - name: Install Packages
    yum:
      name: "{{item}}"
      state: present
    with_items:
      - java-1.8.0

  - name: Download Tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.105/bin/apache-tomcat-9.0.105.tar.gz
      dest: /home/user1/
      mode: 0777
      owner: user1
      group: user1

  - name: Extract Tomcat
    unarchive:
      src: /home/user1/apache-tomcat-9.0.105.tar.gz
      dest: /home/user1/
      owner: user1
      group: user1
      remote_src: yes

  - name: Copy tomcat users file to tomcat server
    copy:
      src: tomcat-users.xml
      dest: /home/user1/apache-tomcat-9.0.105/conf/tomcat-users.xml

  - name: Start Tomcat
    shell: startup.sh
    args:
      chdir: /home/user1/apache-tomcat-9.0.105/bin
